name: MeanExpressionNN
label: MEAN_ESTIMATION_MAELOSS
kwargs:
  observables_dimension: 76
  hidden_dimensions: [100, 100]
  latent_dimension: 84
  loss_type: "mae"
  mask_cells_prop: 0.0
  mask_genes_prop: 0.0
  responses: 0
