name: MonetAutoencoder2D
label: 10_24_2021
kwargs:
  observables_dimension: 155
  hidden_dimensions: [200, 200] # try (20, 100, 200) and all 155
  latent_dimension: 155 # try (20, 100, 200) and all 155
  loss_type: "mae" # laplace (Mae) would be better
  other_logged_losses: ["mae_response", "mse"]
  dim: 2
  kernel_size: 25
  mask_cells_prop: 1.0
  mask_genes_prop: 0.0
  responses: 0
