# @package _group_
name: MonetAutoencoder2D # add poetry nbstripout
label: mae_test # BEFORE training clean checkpoints folder
kwargs:
  observables_dimension: 160
  hidden_dimensions: [50, 25] # try (20, 100, 200) and all 160
  latent_dimension: 10 # try (20, 100, 200) and all 160
  loss_type: "mse" # laplace (Mae) would be better
  dim: 2
  kernel_size: 25
  mask_cells_prop: 0.0
  mask_genes_prop: 0.0
