name: MonetDense
kwargs:
  observables_dimension: 155
  hidden_dimensions: [128, 128] # try (20, 100, 200) and all 155
  latent_dimension: 155
  loss_type: "mae" # laplace (Mae) would be better
  other_logged_losses: ["mse"]
  dim: 1
  kernel_size: 25
  mask_random_prop: 0.0
  mask_cells_prop: 0.0
  mask_genes_prop: 1.0
  response_genes: # empty by default this is none so we can use the responses from the data
  celltypes:
  batchnorm: True
  final_relu: False
  attach_mask: False
  dropout: 0
  responses: True
  hide_responses: True
