name: MonetDense
_includes_celltypes: ${datasets.dataset.include_celltypes}
kwargs:
  observables_dimension: ${conditional:${model._includes_celltypes},170,154} # 16 more than the 154 genes because of the one hot encoded celltypes if they are to be included
  hidden_dimensions: [512, 512, 512, 512, 512, 512]
  output_dimension: 1
  loss_type: "mse"
  other_logged_losses: ["mse"]
  dim: 2
  kernel_size: 15
  radius: ${radius}
  mask_random_prop: 0.0
  mask_cells_prop: 0.0
  mask_genes_prop: 1.0
  response_genes: [0] # empty by default this is none so we can use the responses from the data (here it matches the output dimension)
  celltypes:
  batchnorm: True
  final_relu: False
  attach_mask: False
  dropout: 0
  responses: True
  hide_responses: True
  include_skip_connections: True
  aggr: "sum"
  pseudo_mode: "polar"
