# @package _group_
name: MonetAutoencoder2D
label: FINAL_RESULT_W_NEIGHBORS
kwargs:
  observables_dimension: 160
  hidden_dimensions: [200, 200] # try (20, 100, 200) and all 160
  latent_dimension: 200 # try (20, 100, 200) and all 160
  loss_type: "mae" # laplace (Mae) would be better
  dim: 2
  kernel_size: 25
  mask_cells_prop: 0.0
  mask_genes_prop: 0.0
