name: MonetAutoencoder2D
label: 10_24_2021
kwargs:
  observables_dimension: 155
  hidden_dimensions: [200, 200] # try (20, 100, 200) and all 155
  latent_dimension: 155 # try (20, 100, 200) and all 155
  loss_type: "mae_response" # laplace (Mae) would be better
  other_logged_losses: ["mae", "mse"]
  dim: 1
  kernel_size: 25
  mask_cells_prop: 0.0
  mask_genes_prop: 1.0
  responses: [93] # empty by default this is none so we can use the responses from the data
  celltype_lookup: 0 # this gets updated in train
  batchnorm: True
  final_relu: False
  dropout: 0.05
