name: TrivialAutoencoder
kwargs:
  observables_dimension: 155
  hidden_dimensions: [200, 200]
  latent_dimension: 10
  loss_type: "mae"
  other_logged_losses: ["mse"]
  mask_random_prop: 0.0
  mask_cells_prop: 0.0
  mask_genes_prop: 1.0
  response_genes: # by default this is none so we can use the responses from the data
  celltypes:
  batchnorm: True
  final_relu: False
  attach_mask: False
  dropout: 0
  responses: True
  hide_responses: True
  include_skip_connections: False
