name: TrivialAutoencoder
kwargs:
  observables_dimension: 155
  hidden_dimensions: [200, 200]
  latent_dimension: 10
  loss_type: "mae"
  other_logged_losses: ["mae_response", "mse"]
  mask_random_prop: 0.0
  mask_cells_prop: 0.0
  mask_genes_prop: 1.0
  responses: # by default this is none so we can use the responses from the data
  celltype_lookup: 0
  batchnorm: True
  final_relu: False
  dropout: 0.05
  input_dropout_only: True
