# @package _group_
name: TrivialAutoencoder
label: TrivialAutoencoder
kwargs:
  observables_dimension: 160
  hidden_dimensions: [50, 25]
  latent_dimension: 10
  loss_type: "mse"
  mask_cells_prop: 0.0
  mask_genes_prop: 0.0
