repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
