# @package _group_
bands:
  - 2

# i/o parameters
verbose: True
checkpoint: ${paths.root}
device: "cuda:${gpus.0}"
output_file: "${paths.data}/var_params.pt"
batch_size: 1
save_model_summary: True

# coverage for tests
testing: False
