plotting: True
n_epochs: 600
logger_name: table2
save_model_summary: False
batch_size: 1
dropout: True
early_stopping: True
log_transform: True
seed: False
trainer:
  profiler: simple
  logger: True
  enable_checkpointing: True
  reload_dataloaders_every_epoch: False
  gpus: ${gpus}
  auto_select_gpus: False
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 10
#  strategy: dp
  log_every_n_steps: 10
filepath: ${model.name}__${model.kwargs.hidden_dimensions}__${radius}__${training.logger_name}
