# @package _group_
plotting: True
n_epochs: 600
logger_name: 'logs_08_11_2021'
save_model_summary: True
batch_size: 2
trainer:
  profiler: null
  logger: True
  checkpoint_callback: True
  reload_dataloaders_every_epoch: False
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: ${gpus}
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 10
