plotting: True
n_epochs: 1200
logger_name: DEFAULTNAME
save_model_summary: False
batch_size: 1
dropout: True
early_stopping:
  monitor: "val_loss"
  min_delta: 0.00
  patience: 10
  verbose: False
  mode: "min"
log_transform: True # why is this not in the data section....
seed: False
trainer:
  profiler: simple
  logger: True
  enable_checkpointing: True
  gpus: ${gpus}
  accelerator: "gpu"
  # strategy: "deepspeed_stage_2_offload"
  auto_select_gpus: False
  max_epochs: ${training.n_epochs}
  min_epochs: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
filepath: ${model.name}__${model.kwargs.hidden_dimensions}__${radius}__${training.logger_name}__${optimizer.name} #__${model.kwargs.aggr}
complete_data: True
