# @package _group_
plotting: True
n_epochs: 10
logger_name: 'lightning_logs'
save_model_summary: True
trainer:
  profiler: null
  logger: True
  checkpoint_callback: True
  reload_dataloaders_every_epoch: False
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  gpus: ${gpus}
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 10
