# @package _group_
plotting: True
n_epochs: 150
logger_name: 'logs_10_24_2021'
save_model_summary: True
batch_size: 1
early_stopping: True
log_transform: True
trainer:
  profiler: simple
  logger: True
  checkpoint_callback: True
  reload_dataloaders_every_epoch: False
  gpus: ${gpus}
  auto_select_gpus: False
  max_epochs: ${training.n_epochs}
  min_epochs: ${training.n_epochs}
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 10
  accelerator: dp
