dataset:
  _target_: spatial.merfish_dataset.FilteredMerfishDataset
  root: ${paths.data}
  n_neighbors: ${n_neighbors}
  train: True
  log_transform: True
  neighbor_celltypes: False
  radius: ${radius}
  non_response_genes_file: "/home/roko/spatial/spatial/non_response_blank_removed.txt"
  animals:
  bregmas:
  sexes:
  behaviors:
  test_animal: 1
  full_animal_holdout: True
  splits: 1

predictor_genes: ${paths.root}/spatial/non_response.txt
