dataset:
  _target_: spatial.merfish_dataset.SyntheticDataset10
  root: ${paths.data}
  n_neighbors: ${n_neighbors}
  train: True
  log_transform: True
  include_celltypes: False
  radius: ${radius}
  non_response_genes_file: "/home/roko/spatial/spatial/non_response_blank_removed.txt"
  splits: 2

predictor_genes: ${paths.root}/spatial/non_response.txt
