defaults:
  - optimizer: sgd
  - datasets: FilteredMerfishDataset
  - model: MonetAutoencoder2D
  - training: default
  - predict: default

mode: train

n_neighbors: 3

gpus:
  - 0


paths:
  root: ${env:SPATIAL_HOME}
  data: ${paths.root}/data
  models: ${paths.root}/models
  output: ${paths.root}/output

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: '0,1,2,3,4,5,6,7'
  output_subdir: null
  run:
    dir: .
