defaults:
  - _self_
  - optimizer: adam
  - datasets: DemoDataset
  - model: MonetDenseDemo
  - training: default
  - predict: default

mode: train

n_neighbors: 3

radius: 5

gpus: [0] # len(CUDA_V_D) - 1


paths:
  root: .
  data: demo_data
  models: models
  output: output

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: '0'
      CUDA_LAUNCH_BLOCKING: 1
  output_subdir: null
  run:
    dir: .
